name: Send Daily Motivational Quote

on:
  push:
    branches:
      - master

jobs:
  send_motivation:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch and Send Motivational Quote
        run: |
          # Get quote and author
          response=$(curl -s https://zenquotes.io/api/random)
          quote=$(echo "$response" | jq -r '.[0].q')
          author=$(echo "$response" | jq -r '.[0].a')

          # Create JSON payload safely with jq
          payload=$(jq -n \
            --arg text "🌟 *Daily Motivation* 🌟\n\n_${quote}_\n\n– *$author*" \
            '{text: $text}')

          # Send to Slack
          curl -X POST -H 'Content-type: application/json' \
          --data "$payload" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
