name: Send Daily Motivational Quote

on:
  schedule:
    - cron: '30 9 * * 1-5'

jobs:
  send_motivation:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Quote and Send to Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          # Fetch the quote
          response=$(curl -s https://zenquotes.io/api/random)
          
          # Parse the quote and author
          quote=$(echo "$response" | jq -r '.[0].q')
          author=$(echo "$response" | jq -r '.[0].a')

          # Send to Slack with proper newlines
          curl -X POST -H "Content-type: application/json" \
            --data "$(jq -n --arg text "🌟 Daily Motivation 🌟

_${quote}_

– $author" '{text: $text}')" \
            "$SLACK_WEBHOOK"
