name: Daily Motivation

on:
  schedule:
    - cron: '30 9 * * 1-5' # Weekdays at 9:30 AM UTC

jobs:
  send-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Quote and Send to Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          # Fetch a random motivational quote
          response=$(curl -s https://zenquotes.io/api/random)

          # Extract the quote and author using jq
          quote=$(echo "$response" | jq -r '.[0].q')
          author=$(echo "$response" | jq -r '.[0].a')

          # Escape quotes and construct a multi-line message
          message="🌟 Daily Motivation 🌟

_${quote}_

– $author"

          # Use a heredoc to safely format JSON payload
          curl -X POST -H "Content-type: application/json" \
          -d @- "$SLACK_WEBHOOK" <<EOF
{
  "text": "$message"
}
EOF
