name: Daily Motivation

on:
  schedule:
    - cron: '30 9 * * 1-5' # Every weekday at 9:30 AM UTC

jobs:
  send-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Quote and Send to Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          # Fetch the quote
          response=$(curl -s https://zenquotes.io/api/random)

          # Parse the quote and author using jq
          quote=$(echo "$response" | jq -r '.[0].q')
          author=$(echo "$response" | jq -r '.[0].a')

          # Construct message with real line breaks (not \n)
          message="🌟 Daily Motivation 🌟

_${quote}_

– $author"

          # Post to Slack
          payload=$(jq -n --arg text "$message" '{text: $text}')

          curl -X POST -H "Content-type: application/json" \
            --data "$payload" \
            "$SLACK_WEBHOOK"
